### ISSUE TITLE
Если запрашивается больше, чем есть, возвращайте 0

### ISSUE THREAD

**Issue by coursar** [ILYINGK/ATM3#1]
https://github.com/ILYINGK/ATM3/blob/3da6bb7a4509a765bcc54a0dfac514ebbdb86187/src/ATM.java#L9-L11

**Comment by ILYINGK** [comment]
if (amount>count){
            return 0;
        }

**Comment by ILYINGK** [comment]
if (amount>count){
            return 0;
        }
логичнее отдавать состояние счета, потому что мы можем обнулить счет или запросить большую сумму, а ответ будет один....
вероятность конечно не велика...
